## solution 1

In [15]:
import numpy as np # Library import operation

def V_to_M(x,N): # Function
    matrix = np.column_stack([x**(N-i-1) for i in range(4,-1,-1)]) # matrix generator based on the given requirement.
    print(matrix)


a=np.array([1,2,3,4,5]) # the vactor
b=5 
V_to_M(a,b) # Function calling

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


## solution 2

In [35]:
def avg(a,k,n):
    
    lis=[];
    avg_list=[];
    for i in range(n-k+1):
        
        for j in range(k):
            
            lis.append(a[i+j])
            
        avg=np.sum(lis)/k
        avg_list.append(avg)
        
    print("List of average values" , avg_list)
    print("The moving average sequence has", len(avg_list) , "values")
            
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
n=13

avg(a,k,n)

List of average values [5.0, 9.666666666666666, 15.333333333333334, 22.0, 31.666666666666668, 60.333333333333336, 109.66666666666667, 182.33333333333334, 266.3333333333333, 359.6666666666667, 476.0]
The moving average sequence has 11 values
